name: 'check'
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  yarn install
                  yarn check:all
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                  milliseconds: 1000
